Add new targets for public build
tiiuae/FMO-OS pull request #13
Opened 2024-02-29 13:22 UTC by buianhhuy96

- Add "updateAttrs" as custom update attributes and lists method, that allow to concatenate lists instead of overwriting them (like lib.recursiveUpdate)
- Add public targets which has a "extend" that indicates the target that they are based on.
- Reconfigure "config-processor-hardware" and "config-processor-installer" for new public targets

2024-02-29 13:44 UTC, jsvapiav requested changes

2024-02-29 13:44 UTC, jsvapiav commented on hardware/fmo-os-rugged-laptop-7330-public.nix
> +  sysconf = let updateAttrsAndLists = (import ../utils/updateAttrsAndLists.nix).updateAttrsAndLists; in
Those files were made as something what could be written by people who do not know nothing about nix.. In one hand, in another hand they defiantly needs a some kind of inheritance mechanism. But I would prefer to hide it somewhere in `config-processor-*.nix`. Maybe we can use here something like:
```
{
    extend = './fmo-os-rugged-laptop-7330.nix)'
    sysconf = .....
}
```
And this one could be interpreted as extension pattern? What do you think?

2024-02-29 13:44 UTC, jsvapiav commented on hardware/fmo-os-rugged-laptop-7330-public.nix
> +  sysconf = let updateAttrsAndLists = (import ../utils/updateAttrsAndLists.nix).updateAttrsAndLists; in
And then all nix magic could be hidden in `config-procrssor` files!

2024-02-29 14:40 UTC, buianhhuy96 commented on hardware/fmo-os-rugged-laptop-7330-public.nix
> +  sysconf = let updateAttrsAndLists = (import ../utils/updateAttrsAndLists.nix).updateAttrsAndLists; in
I think it may be possible. I will try

2024-03-01 11:01 UTC, buianhhuy96 commented
I updated the new approach where the overwriting mechanism is hidden. But I may need suggest for naming files.

`Installer` target, however, is not possible to do that at the moment. This is because the `updateAttrs` method that I wrote only has the option to **overwrite** the old list with new one or **concatenate** both. The installer target requires **concatenate** `extraModules` (where there is `services.registration-agent-laptop`) and **overwrite** `oss` (to not include `fmo-os-rugged-laptop-7330` and `fmo-os-rugged-tablet-7230`)

2024-03-01 12:29 UTC, jsvapiav commented
> I updated the new approach where the overwriting mechanism is hidden. But I may need suggest for naming files.
> 
> `Installer` target, however, is not possible to do that at the moment. This is because the `updateAttrs` method that I wrote only has the option to **overwrite** the old list with new one or **concatenate** both. The installer target requires **concatenate** `extraModules` (where there is `services.registration-agent-laptop`) and **overwrite** `oss` (to not include `fmo-os-rugged-laptop-7330` and `fmo-os-rugged-tablet-7230`)

As I actually suggested for you to make explicit inheritance, but you made implicit magic.. now someone need to know that we have some magic for public and not public builds, or and be able to read or internal nix files.. and actually can not extend it for any other type of builds.. I still would prefer to introduce an *explicit* inheritance which may be used not only for public/private separation, but also for inherit different type of devices from common parent, for ex.

2024-03-01 12:30 UTC, jsvapiav requested changes

2024-03-01 12:30 UTC, jsvapiav commented on utils/updateAttrs.nix
One more thing that I don't like here is this. Are you sure that default nix library does not have any *updateAttrs* implementation?

2024-03-04 08:28 UTC, buianhhuy96 commented on utils/updateAttrs.nix
There is `recursiveUpdate` and `//` operator.
However, they have their own flaws. 
`//` operator overrides every child config, meaning that we have to rewrite everything including the child configs which we don't want to disable or modify. For example, if we want to rewrite dockervm, as soon as it reads `vms` (the parent most config), it overwrites the whole `vms`, not just `vms.dockervm...`
`recursiveUpdate` and `//` both cannot concatenate arrays, but overwrite the whole array. Meaning that, when I want to disable a service in `extraModule` (which is written as array), I need to rewrite everything in `extraModule`. 

Another issue with `recursiveUpdate` is that it requires `nixpkgs`. But our fmo config files are written in the form of a `set` (nix `set`). `lib.recursiveUpdate` will turn it into a function, which is then only evalutated during building and the files cannot be imported in flake as they are right now (`import ./hardware/...`), we'll have to rewrite `flake.nix` too

2024-03-04 09:01 UTC, buianhhuy96 commented
I rewrite it with a `sysconf.based` to indicate the based version of the public builds.

2024-03-05 10:17 UTC, jsvapiav requested changes

2024-03-05 10:17 UTC, jsvapiav commented on hardware/fmo-os-rugged-laptop-7330-public.nix
> +    based = (import ./fmo-os-rugged-laptop-7330.nix);
I would prefer to use here something more common: `extend = ` instead of `based = `. All other looks super good!

2024-03-05 10:30 UTC, jsvapiav commented on hardware/fmo-os-rugged-laptop-7330-public.nix
> +    based = (import ./fmo-os-rugged-laptop-7330.nix);
Of yeah, one more. So sorry for that, please do not use nix language here, so:
```
extend = './fmo-os-rugged-laptop-7330.nix';
```
and use import in config-processor file

2024-03-05 10:32 UTC, jsvapiav requested changes

2024-03-05 10:32 UTC, jsvapiav commented on config-processor-hardware.nix
> +  targetconf = if lib.hasAttr "based" sysconf
BTW, the same need to be done for `config-processor-installer` as well.

2024-03-05 10:36 UTC, buianhhuy96 commented on hardware/fmo-os-rugged-laptop-7330-public.nix
> +    based = (import ./fmo-os-rugged-laptop-7330.nix);
I will modify this.
About `recursiveUpdate`, it understands arrays as the value of a key in a set. Therefore, it will replace the old array (old value) with new array (new value) and does not care about what inside the array. I would take one example:

1. In `fmo-os-rugged-tablet-7230`, we have:
```
sysconf.vms.dockervm = {
extraModules = [
      {
        users.users."ghaf".extraGroups = ...;
        microvm = ...;
        services.fmo-dci = ...;
        services.registration-agent-laptop = ...;
      }
    ]; # extraModules;
}
```
2. We want to disable `services.registration-agent-laptop.enable = false;` with 
```
sysconf.vms.dockervm = {
extraModules = [
      {
        services.registration-agent-laptop.enable = false;
      }
    ]; # extraModules;
}
```

=> The result of using `recursiveUpdate` is
```
sysconf.vms.dockervm = {
extraModules = [
      {
        services.registration-agent-laptop.enable = false;
      }
    ]; # extraModules;
}
```

`updateAttrs` checks if the arrays contain sets (array of sets), it will perform `updateAttrs` in those sets. In case of no arrays, what it does is exactly the same as `recursiveUpdate`

2024-03-05 10:44 UTC, buianhhuy96 commented on config-processor-hardware.nix
> +  targetconf = if lib.hasAttr "based" sysconf
For installer, I does not really have an optimal solution because:
The public version needs: 
```
sysconf = {
    **extraModules** = [
      {
        services = {
          registration-agent-laptop ={
            enable = false;
          };
        };
      }
    ]; # extraModules

   installer = {...};

    **oss** = [
      "fmo-os-rugged-laptop-7330-public"
      "fmo-os-rugged-tablet-7230-public"
    ]; # oss
  }; # system
```

In which the `extraModules` needs to be a result of array **concatenation**, meaning: keep every other `extraModule` configs but disable registration-agent-laptop, while the `oss` need to be completely **replaced**, not concatenated, so that the public installer won't include the main (private) fmo-os version. 
So for now, the public installer version is a copy-paste of main installer version with some removal of private usage.

2024-03-05 10:53 UTC, buianhhuy96 commented on config-processor-hardware.nix
> +  targetconf = if lib.hasAttr "based" sysconf
It still, however, possible that we pay special care for the `oss`. For example, in the `config-processor-installers`, I could read the `oss` from the current sysconf, not the result of updateAttrs. 
Although it's a bit hardcoded, if you want it, I can do that way.

2024-03-05 11:23 UTC, jsvapiav approved these changes
Good job! Let's merge it!

2024-03-06 09:04 UTC, merged